data_dir: !!python/object/apply:pathlib.PosixPath
- /
- home
- dl370
- agent
- dataset
desc_file: !!python/object/apply:pathlib.PosixPath
- /
- home
- dl370
- agent
- aideml
- exp
- desp_flex.txt
goal: null
eval: Use Mean Squared Error (MSE) between predicted and true spectra.
log_dir: !!python/object/apply:pathlib.PosixPath
- /
- home
- dl370
- agent
- aideml
- exp
- logs
- 2-fierce-griffin-of-action
workspace_dir: !!python/object/apply:pathlib.PosixPath
- /
- home
- dl370
- agent
- aideml
- exp
- workspaces
- 2-fierce-griffin-of-action
preprocess_data: true
copy_data: true
exp_name: 2-fierce-griffin-of-action
exec:
  timeout: 36000
  agent_file_name: runfile.py
  format_tb_ipython: false
generate_report: true
report:
  model: o1
  temp: 1.0
agent:
  steps: 200
  k_fold_validation: 5
  expose_prediction: false
  data_preview: true
  code:
    model: o1
    temp: 0.6
  feedback:
    model: o1
    temp: 0.6
  search:
    max_debug_depth: 3
    debug_prob: 0.6
    num_drafts: 5
